### ISSUE TITLE
extra "///" before comment block

### ISSUE THREAD

**Issue by wgy855** [kasecato/vscode-docomment#108]
Click enter in empty line before a comment block will generate extra "///". [version 0.1.16][version 0.1.15]

![image](https://user-images.githubusercontent.com/970803/88615398-726af100-d0c4-11ea-8104-8ab6bd204818.png)

**Comment by kasecato** [comment]
Thank you for your report. I just fixed and released. Please check it.

**Comment by wgy855** [comment]
Problem solved in v0.1.17. Thanks a lot.
