### ISSUE TITLE
Type is detected as parameter

### ISSUE THREAD

**Issue by Torguen** [kasecato/vscode-docomment#113]
A reference to a two-dimensional array is detected as a parameter and its wrong field is created for documentation.
![Captura](https://user-images.githubusercontent.com/19652075/96350882-34c0a780-10b8-11eb-9cc4-6ffdcb976f34.PNG)

**Comment by kasecato** [comment]
@Torguen Thank you for your detailed report! Sorry for my late reply, but I just fixed it and released it [v.0.1.19](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment). Please check it 👍
