### ISSUE TITLE
I cant get this extension working

### ISSUE THREAD

**Issue by benitazz** [kasecato/vscode-docomment#62]
I'm using VS code 1.22.2 on Windows 10
I have created ASP.net core project
Installed C# XML Documentation 
configured the User settings:
                                   // Press the Enter key to activate a command (Default: false)
                                     "docomment.activateOnEnter": true,
                                  // Insert spaces when pressing Tab.
                                      "editor.insertSpaces": true,
                                  // The number of spaces a tab is equal to.
                                   "editor.tabSize": 4

So when I type "///" nothing happens, please assist.

**Comment by benitazz** [comment]
I will try, thanks

**Comment by benitazz** [comment]
I have tried and installed v.0.0.19 and still does not work

**Comment by kasecato** [comment]
@benitazz Is the file extension `.cs`? Or try `docomment.activateOnEnter: false`

**Comment by kasecato** [comment]
- VSCode 1.22.2
- Win 10
- vscode-docomment v0.0.19
![win_csharp_doccomennt_vscode1 22 2](https://user-images.githubusercontent.com/10364603/39433353-9a46043c-4cd0-11e8-926e-5777efe834d5.gif)

**Comment by benitazz** [comment]
Thank you,I got it working. The problem was that I put in the settings in both the user settings and workspace settings, once I removed the settings in workspace settings then everything started working like expected.

**Comment by navybrmi** [comment]
I have the same exact issue. And I verified, as per @benitazz, that the settings are updated in user settings and not in workspace settings.
