### ISSUE TITLE
Incorrect for properties

### ISSUE THREAD

**Issue by lonix1** [kasecato/vscode-docomment#68]
Properties should not have `<returns></returns>`, however this is generated:

````csharp
/// <summary>
/// 
/// </summary>
/// <returns></returns>           // this should not be generated
public string Foo { get; set; }

/// <summary>
/// 
/// </summary>
/// <returns></returns>            // this should not be generated
public string Bar { get; set; } = "bar";
````

**Comment by jsmith-jxe** [comment]
@kasecato are you working on this? If not, I can take a crack at it!

**Comment by kasecato** [comment]
@lonix1 @jsmith-jxe Thank you for reporting and supporting 👍 I just released v0.1.1, please check it 🙇‍♂️

**Comment by lonix1** [comment]
@kasecato Thanks for working so quickly on this.

However... the `<value>` attribute (although recommended by the .NET guidelines) is VERY uncommon. Hardly any codebase uses it, because just like `<returns>`, it simply adds noise, and adds no value to a property's `<summary>`. Most people will hit `///` and then immediately have to delete that line. :laughing: 

It should be an option, but not generated by default. What we now have is one noisy attribute replacing another, but the same result. :smile: 

Just a suggestion, I still think this extension is great, saves lots of time. Thanks again.

**Comment by ericfoxx** [comment]
@lonix1 @kasecato I agree -- more user-controllable options around doc generation would be amazing. In this case, I could see:
```json
"docomment.advanced": {
    "cs.property" : {
        "attributes" : ["summary"],
        "inline" : "true",
    },
    "cs.method" : {
        "attributes" : ["summary","param","returns"],
        "inline" : "false",
    },
},
```
See what I mean?

**Comment by kasecato** [comment]
@ericfoxx @lonix1 I just added and released user-controllable options.
```json
// User-controllable options
"docomment.advanced": {
    "cs": {
        "namespace" : {
            "attributes" : ["summary"]
        },
        "class" : {
            "attributes" : ["summary", "typeparam"]
        },
        "interface" : {
            "attributes" : ["summary", "typeparam"]
        },
        "struct" : {
            "attributes" : ["summary"]
        },
        "enum" : {
            "attributes" : ["summary"]
        },
        "delegate" : {
            "attributes" : ["summary", "param", "typeparam", "returns"]
        },
        "field" : {
            "attributes" : ["summary"]
        },
        "property" : {
            "attributes" : ["summary", "value"]
        },
        "method" : {
            "attributes" : ["summary", "param", "typeparam", "returns"]
        },
        "event" : {
            "attributes" : ["summary"]
        }
    }
}
```

**Comment by lonix1** [comment]
@kasecato Thanks - it's perfect now! :trophy:
