### ISSUE TITLE
Support delimited comment syntax /** */?

### ISSUE THREAD

**Issue by lmmarsano** [kasecato/vscode-docomment#75]
According to the C♯ specification, there's a [delimited documentation comment syntax][docom], which VS Code supports.
Does this extension support the feature?
If not, could it add support?

[docom]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#introduction

**Comment by kasecato** [comment]
Hi @lmmarsano 

I tried implementing delimited comment syntax. Please try it.

.vscode/settings.json
```json
"docomment.syntax": "delimited",
```

Thanks

**Comment by lmmarsano** [comment]
@kasecato Thanks, this is impressive!
Some issues I notice:
1. Typing `/**` above a declaration inserts an extra `* ` on the next line:
	```C#
	/**
	```
	becomes
	```C#
	/**
	*  * <summary>
	 * 
	 * </summary>
	 */
	```
2. Entering a newline after `*/` inserts `* ` before the cursor:
	```C#
	*/
	```
	becomes
	```C#
	*/
	* 
	```

I would contribute test cases, but I don't know enough vscode API yet.

**Comment by kasecato** [comment]
@lmmarsano Thanks for using the feature! 

- `1.`  It's reproduced.
    - When changed `docoment.syntax` on the fly that is only not restarting VS Code
        - I fixed it 🔨
- `2.` It's reproduced
    - The same as single-line
        - I fixed it 🔨

**Comment by lmmarsano** [comment]
@kasecato Thanks, again.
Another issue (sorry not to find this sooner):
- *Activate On Enter*: With setting `"docomment.activateOnEnter": true`, `/**` <kbd>Enter</kbd> does not expand into documentation.
	```C#
	/**
	```
	<kbd>Enter</kbd> becomes
	```C#
	/**
	 */
	```
	`/*` automatically expands into `/* */`, which might cause the issue.

That's everything I can find.

**Comment by kasecato** [comment]
@lmmarsano I appreciate your contribution 👍 I fixed it 🔨

**Comment by lmmarsano** [comment]
Works great: I think we can safely close this issue.
Thanks!
