### ISSUE TITLE
Extra `///` added when undoing line deletion

### ISSUE THREAD

**Issue by WebFreak001** [kasecato/vscode-docomment#93]
when you have any documentation like
![documentation](https://user-images.githubusercontent.com/2035977/85291158-7179ea80-b49a-11ea-832b-ef8a97ef9d8b.png)

select some line like this
![selected line in documentation](https://user-images.githubusercontent.com/2035977/85291255-8eaeb900-b49a-11ea-8840-747a4ef0bd20.png)

and then delete that line
![empty documentation](https://user-images.githubusercontent.com/2035977/85291204-835b8d80-b49a-11ea-986b-c81b7ad15506.png)

when you now press undo (ctrl-z) depending on where your selection started (at start or end of selection) you will now either get
![bug on start of selection](https://user-images.githubusercontent.com/2035977/85291346-ad14b480-b49a-11ea-9f20-da75f21bb06f.png)
or
![bug on end of selection](https://user-images.githubusercontent.com/2035977/85291370-b56cef80-b49a-11ea-94aa-5bcf54c31893.png)

**Comment by kasecato** [comment]
Hello @WebFreak001 , sorry for my late reply. I just fixed it and released [v0.1.13](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment), please check it 👍

**Comment by kasecato** [comment]
@WebFreak001 Any updates? I'll close it tomorrow.

**Comment by WebFreak001** [comment]
ah sorry, it's fixed yes
