### ISSUE TITLE
Enter behind <summary>, input too many "///"！

### ISSUE THREAD

**Issue by wlfsky** [kasecato/vscode-docomment#95]
Behind “/// <summary>” input "Enter" key
"
	/// <summary>
/// 	
 ///    ///  *******
"
There is an extra "///".

**Comment by wlfsky** [comment]
`/// <summary>` input "Enter"
`///  <summary>
///  
/// /// *****
`

**Comment by wlfsky** [comment]
`/// <summary>` "Enter" key
`/// <summary>`
`///`
`/// /// *****`

**Comment by kasecato** [comment]
@wlfsky Sorry for my late reply. I can't reproduce the problem. Could you share a animation GIF?
![#95](https://user-images.githubusercontent.com/10364603/87853627-ae74b800-c946-11ea-9081-5ca897054e22.gif)

**Comment by wlfsky** [comment]
This time is different!
![buggif](https://user-images.githubusercontent.com/5280303/87900648-9b1d3600-ca87-11ea-82dc-364ed04da796.gif)

**Comment by wlfsky** [comment]
![buggif2](https://user-images.githubusercontent.com/5280303/87901320-509cb900-ca89-11ea-846b-0bf9fe33b7d4.gif)

**Comment by wlfsky** [comment]
![buggif2](https://user-images.githubusercontent.com/5280303/87901381-732ed200-ca89-11ea-9cde-7bb458ae7dd5.gif)

**Comment by kasecato** [comment]
@wlfsky Big thanks! I just released [v0.1.14](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment). I'm not too sure yet, so I'll release it once more if you can find something. 🔨

**Comment by wlfsky** [comment]
Nice work! Thank you very much!
